# Generated by Django 3.2.2 on 2021-05-08 10:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('WORLD', 'world'), ('ENVIRONMENT', 'environment'), ('TECHNOLOGY', 'technology'), ('DESIGN', 'design'), ('CULTURE', 'culture'), ('TRAVEL', 'travel'), ('STYLE', 'style'), ('HEALTH', 'health'), ('SCIENCE', 'science'), ('OPINION', 'opinion'), ('POLITICS', 'politics'), ('BUSINESS', 'business')], default='world', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('image', models.URLField(max_length=500)),
                ('excerpt', models.CharField(max_length=150)),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('day', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('breaking', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogentries', to='blog.category')),
            ],
        ),
    ]
